version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:17.0.1-ce.0
    container_name: gitlab
    hostname: ${GITLAB_HOST}
    restart: unless-stopped
    shm_size: "256m"

    environment:
      TZ: ${TZ}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL}

      # ► Omnibus gitlab.rb
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOST}"
        # Віддаємо HTTP усередині кластера, TLS немає
        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        # SMTP (беремо з env)
        gitlab_rails['gitlab_email_enabled'] = ${SMTP_ENABLED}
        gitlab_rails['smtp_enable']         = ${SMTP_ENABLED}
        gitlab_rails['smtp_address']        = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port']           = ${SMTP_PORT}
        gitlab_rails['smtp_domain']         = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_user_name']      = "${SMTP_USER}"
        gitlab_rails['smtp_password']       = "${SMTP_PASS}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from']   = "${SMTP_USER}"

        # IP-allowlist (опційно)
        gitlab_rails['ip_whitelist'] = [ "${ALLOWED_IPS}" ]

    # volumes:
    #   - ./gitlab/config:/etc/gitlab
    #   - ./gitlab/data:/var/opt/gitlab
    #   - ./gitlab/logs:/var/log/gitlab
    volumes:
      - gitlab-data:/var/opt/gitlab           # ← named volume,  а не ./gitlab/data
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab

    networks:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: gitlab-proxy
    depends_on: [gitlab]
    restart: unless-stopped

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    ports:
      - "80:80"          # тільки HTTP

    networks:
      - backend
      - frontend

  gitlab-backup:                 # ← sidecar для щоденного бекапу
      image: busybox:1.36
      container_name: gitlab-backup
      depends_on: [gitlab]
      restart: unless-stopped
      entrypoint: >
        /bin/sh -c '
          echo "[backup] sidecar started";
          while true; do
            TS=$(date +%F_%H-%M);
            echo "[backup] $TS  running gitlab-backup create...";
            docker exec gitlab gitlab-backup create STRATEGY=copy;

            LATEST=$(docker exec -t gitlab \
                      ls -1t /var/opt/gitlab/backups | head -n1 | tr -d "\r");
            mkdir -p /export/$TS;
            docker cp gitlab:/var/opt/gitlab/backups/$LATEST   /export/$TS/
            docker cp gitlab:/etc/gitlab/gitlab-secrets.json   /export/$TS/
            docker cp gitlab:/etc/gitlab/gitlab.rb             /export/$TS/

            # тримаємо лише 7 днів
            find /export -maxdepth 1 -type d -mtime +7 -exec rm -rf {} +
            echo "[backup] done — sleep 24h"; sleep 86400;
          done'
      volumes:
        - ./backups:/export               # ← папка з архівами на хості
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        - backend                         # бачить gitlab по імені


networks:
  backend:
  frontend:

volumes:          # <-- додайте нижче
  gitlab-data:
  gitlab-config:
  gitlab-logs:

